from flask_wtf import FlaskForm
from wtforms import IntegerField, SelectField, SubmitField
from wtforms.validators import InputRequired


class SelectionForm(FlaskForm):
    '''Selection fields'''

    start_amount = IntegerField('Amount:', validators=[InputRequired()])
    from_currency = SelectField('From:', choices=[
                               ('CAD', 'Canadian Dollar (CAD)'),
                               ('HKD', 'Hong Kong Dollar (HKD)'),
                               ('ISK', 'Icelandic Króna (ISK)'),
                               ('PHP', 'Philippine Peso (PHP)'),
                               ('DKK', 'Danish Krone (DKK)'),
                               ('HUF', 'Hungarian Forint (HUF)'),
                               ('CZK', 'Czech Koruna (CZK)'),
                               ('GBP', 'Pound Sterling (GBP)'),
                               ('RON', 'Romanian Leu (RON)'),
                               ('SEK', 'Swedish Krona (SEK)'),
                               ('IDR', 'Indonesian Rupiah (IDR)'),
                               ('INR', 'Indian Rupee (INR)'),
                               ('BRL', 'Brazilian Real (BRL)'),
                               ('RUB', 'Russian Ruble (RUB)'),
                               ('HRK', 'Croatian Kuna (HRK)'),
                               ('JPY', 'Japanese Yen (JPY)'),
                               ('THB', 'Thai Baht (THB)'),
                               ('CHF', 'Swiss Franc (CHF)'),
                               ('EUR', 'Euro (EUR)'),
                               ('MYR', 'Malaysian Ringgit (MYR)'),
                               ('BGN', 'Bulgarian Lev (BGN)'),
                               ('TRY', 'Turkish Lira (TRY)'),
                               ('CNY', 'Chinese Renminbi (CNY)'),
                               ('NOK', 'Norwegian Krone (NOK)'),
                               ('NZD', 'New Zealand Dollar (NZD)'),
                               ('ZAR', 'South African Rand (ZAR)'),
                               ('USD', 'United States Dollar (USD)'),
                               ('MXN', 'Mexican Peso (MXN)'),
                               ('SGD', 'Singapore Dollar (SGD)'),
                               ('AUD', 'Australian Dollar (AUD)'),
                               ('ILS', 'Israeli New Shekel (ILS)'),
                               ('KRW', 'South Korean Won (KRW)'),
                               ('PLN', 'Polish Złoty (PLN)'),
                               ])
    to_currency = SelectField('To:', choices=[
                               ('CAD', 'Canadian Dollar (CAD)'),
                               ('HKD', 'Hong Kong Dollar (HKD)'),
                               ('ISK', 'Icelandic Króna (ISK)'),
                               ('PHP', 'Philippine Peso (PHP)'),
                               ('DKK', 'Danish Krone (DKK)'),
                               ('HUF', 'Hungarian Forint (HUF)'),
                               ('CZK', 'Czech Koruna (CZK)'),
                               ('GBP', 'Pound Sterling (GBP)'),
                               ('RON', 'Romanian Leu (RON)'),
                               ('SEK', 'Swedish Krona (SEK)'),
                               ('IDR', 'Indonesian Rupiah (IDR)'),
                               ('INR', 'Indian Rupee (INR)'),
                               ('BRL', 'Brazilian Real (BRL)'),
                               ('RUB', 'Russian Ruble (RUB)'),
                               ('HRK', 'Croatian Kuna (HRK)'),
                               ('JPY', 'Japanese Yen (JPY)'),
                               ('THB', 'Thai Baht (THB)'),
                               ('CHF', 'Swiss Franc (CHF)'),
                               ('EUR', 'Euro (EUR)'),
                               ('MYR', 'Malaysian Ringgit (MYR)'),
                               ('BGN', 'Bulgarian Lev (BGN)'),
                               ('TRY', 'Turkish Lira (TRY)'),
                               ('CNY', 'Chinese Renminbi (CNY)'),
                               ('NOK', 'Norwegian Krone (NOK)'),
                               ('NZD', 'New Zealand Dollar (NZD)'),
                               ('ZAR', 'South African Rand (ZAR)'),
                               ('USD', 'United States Dollar (USD)'),
                               ('MXN', 'Mexican Peso (MXN)'),
                               ('SGD', 'Singapore Dollar (SGD)'),
                               ('AUD', 'Australian Dollar (AUD)'),
                               ('ILS', 'Israeli New Shekel (ILS)'),
                               ('KRW', 'South Korean Won (KRW)'),
                               ('PLN', 'Polish Złoty (PLN)'),
                               ])
    submit = SubmitField('CALCULATE')
